name: kernel_learning
channels:
  - gpytorch
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - botorch
  - gpytorch
  - matplotlib
  - numpy
  - pandas
  - plotly
  - pytorch
  - scikit-learn
  - scipy
  - pip:
    - ax-platform
